library(VGAM)
library(stringr)

AS_sites <- function(file_name){
    if (file.info(file_name)[1] > 0){
        name <-  word(word(file_name,sep = '/',-1), sep = '_', 1)
	    sample <- read.table(file_name)
	    colnames(sample) <- c('chrom','pos','ref','alt','other')
	    sample <- sample[sample$ref + sample$alt + sample$other > 10, ] # remove the number of reads less than 10

	    #draw plots
	    #jpeg(file=str_c(name, ".jpeg"))
        #hist(sample$ref/(sample$ref + sample$alt + sample$other),seq(0,1,by=0.05),freq =  T, col = 7, main = name, xlab = 'allele ratio')
        #dev.off() 
	    set.seed(1)
        if (nrow(sample) != 0){
            sum_counts <- sample$ref + sample$alt + sample$other # total reads of one site
            
            # fit beta-binomial model and estimate overdispersion rho
            all_rho <- {}
            for (i in c(1:30)){
                sse <- {}
                for (rho in c(seq(0,1,0.01))){
                    m <- VGAM::rbetabinom(length(sum_counts), sum_counts, prob = 0.5, rho)
                    dis <- data.frame(table(cut(m/sum_counts,seq(0,1,by=0.05),right = FALSE)))
                    emp <- data.frame(table(cut(sample$ref/sum_counts,seq(0,1,by=0.05),right = FALSE)))
                    sse <- c(sse,sum((dis$Freq - emp$Freq)^2)) # calculate SSE 
                }
                all_rho <- c(all_rho,c(seq(0,1,0.01))[which.min(sse)]) # select the rho corresponding to the least SSE 
            }
            # Choose the maximum number of occurrences of generated rho in 30 cycles
            new_rho <- as.numeric(names(sort(table(all_rho),decreasing = T))[1]) 
            #print(str_c(name,' ',new_rho))
             
            if  (new_rho < 0.15){ # set the threshold of 0.15              
                
                cutoff <- 0.01 # primary P value cutoff
                
                while (TRUE){
                    new_sample <- cbind(sample,dbetabinom(sample$ref,sample$ref + sample$alt + sample$other, 0.5, new_rho))
                    colnames(new_sample) <- c('chrom','pos','ref','alt','other','P')
                    new_sample <- new_sample[order(new_sample$P),]
                    TP_real <- new_sample[new_sample$P < cutoff,] 
                    
                    re <- {} # fdr
                    for (i in c(1:30)){
                        sim <- VGAM::rbetabinom(nrow(sample), sample$ref + sample$alt + sample$other, prob = 0.5, new_rho) # simulation
                        sim_p <- dbetabinom(sim,sample$ref + sample$alt + sample$other, 0.5, new_rho) #simulation p
                        new_sample2 <- cbind(sample,sim_p)
                        colnames(new_sample2) <- c('chrom','pos','ref','alt','other','P')
                        sim_positive <- new_sample2[new_sample2$P < cutoff,]
                        re <- c(re, nrow(sim_positive)/nrow(TP_real)) # calculate fdr 
                    }

                    # If all fdrs generated by 30 cycles are less than 10%, the threshold of P value corresponping to the fdr is selected
                    if (sum(re > 0.1) == 0 | 'NaN' %in% re == TRUE) {
                        write.table(TP_real, file = str_c(name,'.txt'),quote = F, sep = '\t', row.names = FALSE)
                        break
                    }else{
                        cutoff <- cutoff/2 
                    }
                }
            }else{
                print(str_c(name,' ',new_rho))
            } 
        }
	}
}


# example:
#file_name <- '/Users/liying/Desktop/RProjects/results/results_32/ENCDO249ZDZ/ENCFF269RUB_results.txt'
#AS_sites(file_name)
